//
//CAN_ID Table for Cornell Ranger Robot
//Automatically generated by file_read.m
//

#ifndef __H_CAN_ID__
#define __H_CAN_ID__ 

typedef enum can_ids{
	ID_TIMESTAMP = 0,	 //0 2 1 Timestamp
	ID_ERROR_MB = 1,	 //0 1 0 
	ID_ERROR_CSR = 2,	 //0 2 1 
	ID_ERROR_MCH = 3,	 //0 3 1 
	ID_ERROR_MCFO = 4,	 //0 4 1 
	ID_ERROR_MCFI = 5,	 //0 5 1 
	ID_ERROR_MCSO = 6,	 //0 6 1 
	ID_ERROR_MCSI = 7,	 //0 7 1 
	ID_ERROR_UI = 8,	 //0 8 1 
	ID_MB_STATUS = 9,	 //0 1 3;4;5;6;7;8 
	ID_MCH_MOTOR_VELOCITY = 10,	 //0 3 1 
	ID_MCH_MOTOR_CURRENT = 11,	 //0 3 1 
	ID_MCH_MOTOR_POSITION = 12,	 //0 3 1 
	ID_MCH_MOTOR_TARGET_CURRENT = 13,	 //0 1 3 
	ID_MCH_ANGLE = 14,	 //0 3 1 
	ID_MCH_BATT_POWER = 15,	 //0 3 1 
	ID_MCH_SHUTDOWN = 16,	 //0 1 3 
	ID_MCH_SLEEP = 17,	 //0 1 3 
	ID_MCH_COMMAND_CURRENT = 18,	 //0 1 3 
	ID_MCH_STIFFNESS = 19,	 //0 1 3 
	ID_MCH_DAMPNESS = 20,	 //0 1 3 
	ID_MCH_ANG_RATE = 21,	 //0 3 1 
	ID_MCH_STATUS = 22,	 //0 3 1 
	ID_MCH_EXECUTION_TIME = 23,	 //0 3 1 
	ID_MCH_MAX_EXECUTION_TIME = 24,	 //0 3 1 
	ID_MCH_EMPTY_TX1 = 25,	 //0 1 3 
	ID_MCH_EMPTY_TX2 = 26,	 //0 1 3 
	ID_MCH_BATT_CURRENT = 27,	 //0 3 1 
	ID_MCH_BATT_VOLTAGE = 28,	 //0 3 1 
	ID_MCH_HBRIDGE_TEMP = 29,	 //0 3 1 
	ID_MCH_EMPTY_RX1 = 30,	 //0 3 1 
	ID_MCH_EMPTY_RX2 = 31,	 //0 3 1 
	ID_MCH_EMPTY_RX3 = 32,	 //0 3 1 
	ID_MCFO_MOTOR_POSITION = 33,	 //0 4 1 
	ID_MCFO_MOTOR_VELOCITY = 34,	 //0 4 1 
	ID_MCFO_MOTOR_CURRENT = 35,	 //0 4 1 
	ID_MCFO_MOTOR_TARGET_CURRENT = 36,	 //0 1 4 
	ID_MCFO_RIGHT_ANKLE_ANGLE = 37,	 //0 4 1 
	ID_MCFO_RIGHT_LS = 38,	 //0 4 1 
	ID_MCFO_LEFT_LS = 39,	 //0 4 1 
	ID_MCFO_RIGHT_HS = 40,	 //0 4 1 
	ID_MCFO_LEFT_HS = 41,	 //0 4 1 
	ID_MCFO_SHUTDOWN = 42,	 //0 1 4 
	ID_MCFO_SLEEP = 43,	 //0 1 4 
	ID_MCFO_BATT_POWER = 44,	 //0 4 1 
	ID_MCFO_COMMAND_CURRENT = 45,	 //0 1 4 
	ID_MCFO_STIFFNESS = 46,	 //0 1 4 
	ID_MCFO_DAMPNESS = 47,	 //0 1 4 
	ID_MCFO_STATUS = 48,	 //0 4 1 
	ID_MCFO_LEFT_HEEL_SENSE = 49,	 //0 4 1 
	ID_MCFO_RIGHT_HEEL_SENSE = 50,	 //0 4 1 
	ID_MCFO_EXECUTION_TIME = 51,	 //0 4 1 
	ID_MCFO_MAX_EXECUTION_TIME = 52,	 //0 4 1 
	ID_MCFO_HS_STATE = 53,	 //0 1 4 
	ID_MCFO_EMPTY_TX2 = 54,	 //0 1 4 
	ID_MCFO_BATT_CURRENT = 55,	 //0 4 1 
	ID_MCFO_BATT_VOLTAGE = 56,	 //0 4 1 
	ID_MCFO_HBRIDGE_TEMP = 57,	 //0 4 1 
	ID_MCFO_OUTER_HS = 58,	 //0 4 1 
	ID_MCFO_EMPTY_RX2 = 59,	 //0 4 1 
	ID_MCFO_EMPTY_RX3 = 60,	 //0 4 1 
	ID_MCFI_MOTOR_VELOCITY = 61,	 //0 5 1 
	ID_MCFI_MOTOR_CURRENT = 62,	 //0 5 1 
	ID_MCFI_MOTOR_POSITION = 63,	 //0 5 1 
	ID_MCFI_MOTOR_TARGET_CURRENT = 64,	 //0 1 5 
	ID_MCFI_MID_ANKLE_ANGLE = 65,	 //0 5 1 
	ID_MCFI_RIGHT_LS = 66,	 //0 5 1 
	ID_MCFI_LEFT_LS = 67,	 //0 5 1 
	ID_MCFI_RIGHT_HS = 68,	 //0 5 1 
	ID_MCFI_LEFT_HS = 69,	 //0 5 1 
	ID_MCFI_BATT_POWER = 70,	 //0 5 1 
	ID_MCFI_SHUTDOWN = 71,	 //0 1 5 
	ID_MCFI_SLEEP = 72,	 //0 1 5 
	ID_MCFI_COMMAND_CURRENT = 73,	 //0 1 5 
	ID_MCFI_STIFFNESS = 74,	 //0 1 5 
	ID_MCFI_DAMPNESS = 75,	 //0 1 5 
	ID_MCFI_STATUS = 76,	 //0 5 1 
	ID_MCFI_LEFT_HEEL_SENSE = 77,	 //0 5 1 
	ID_MCFI_RIGHT_HEEL_SENSE = 78,	 //0 5 1 
	ID_MCFI_EXECUTION_TIME = 79,	 //0 5 1 
	ID_MCFI_MAX_EXECUTION_TIME = 80,	 //0 5 1 
	ID_MCFI_HS_STATE = 81,	 //0 1 5 
	ID_MCFI_EMPTY_TX2 = 82,	 //0 1 5 
	ID_MCFI_BATT_CURRENT = 83,	 //0 5 1 
	ID_MCFI_BATT_VOLTAGE = 84,	 //0 5 1 
	ID_MCFI_HBRIDGE_TEMP = 85,	 //0 5 1 
	ID_MCFI_INNER_HS = 86,	 //0 5 1 
	ID_MCFI_EMPTY_RX2 = 87,	 //0 5 1 
	ID_MCFI_EMPTY_RX3 = 88,	 //0 5 1 
	ID_MCSO_MOTOR_CURRENT = 89,	 //0 6 1 
	ID_MCSO_MOTOR_TARGET_CURRENT = 90,	 //0 1 6 
	ID_MCSO_LEFT_ANKLE_ANGLE = 91,	 //0 6 1 
	ID_MCSO_BATT_POWER = 92,	 //0 6 1 
	ID_MCSO_STEER_ANGLE = 93,	 //0 6 1 
	ID_MCSO_SHUTDOWN = 94,	 //0 1 6 
	ID_MCSO_SLEEP = 95,	 //0 1 6 
	ID_MCSO_COMMAND_CURRENT = 96,	 //0 1 6 
	ID_MCSO_STIFFNESS = 97,	 //0 1 6 
	ID_MCSO_DAMPNESS = 98,	 //0 1 6 
	ID_MCSO_STATUS = 99,	 //0 6 1 
	ID_MCSO_EXECUTION_TIME = 100,	 //0 6 1 
	ID_MCSO_MAX_EXECUTION_TIME = 101,	 //0 6 1 
	ID_MCSO_EMPTY_TX1 = 102,	 //0 1 6 
	ID_MCSO_EMPTY_TX2 = 103,	 //0 1 6 
	ID_MCSO_BATT_CURRENT = 104,	 //0 6 1 
	ID_MCSO_BATT_VOLTAGE = 105,	 //0 6 1 
	ID_MCSO_HBRIDGE_TEMP = 106,	 //0 6 1 
	ID_MCSO_EMPTY_RX1 = 107,	 //0 6 1 
	ID_MCSO_EMPTY_RX2 = 108,	 //0 6 1 
	ID_MCSO_EMPTY_RX3 = 109,	 //0 6 1 
	ID_MCSI_MOTOR_CURRENT = 110,	 //0 7 1 
	ID_MCSI_MOTOR_TARGET_CURRENT = 111,	 //0 1 7 
	ID_MCSI_STEER_ANGLE = 112,	 //0 7 1 
	ID_MCSI_BATT_POWER = 113,	 //0 7 1 
	ID_MCSI_SHUTDOWN = 114,	 //0 1 7 
	ID_MCSI_SLEEP = 115,	 //0 1 7 
	ID_MCSI_COMMAND_CURRENT = 116,	 //0 1 7 
	ID_MCSI_STIFFNESS = 117,	 //0 1 7 
	ID_MCSI_DAMPNESS = 118,	 //0 1 7 
	ID_MCSI_STATUS = 119,	 //0 7 1 
	ID_MCSI_EXECUTION_TIME = 120,	 //0 7 1 
	ID_MCSI_MAX_EXECUTION_TIME = 121,	 //0 7 1 
	ID_MCSI_EMPTY_TX1 = 122,	 //0 1 7 
	ID_MCSI_EMPTY_TX2 = 123,	 //0 1 7 
	ID_MCSI_BATT_CURRENT = 124,	 //0 7 1 
	ID_MCSI_BATT_VOLTAGE = 125,	 //0 7 1 
	ID_MCSI_HBRIDGE_TEMP = 126,	 //0 7 1 
	ID_MCSI_EMPTY_RX1 = 127,	 //0 7 1 
	ID_MCSI_EMPTY_RX2 = 128,	 //0 7 1 
	ID_MCSI_EMPTY_RX3 = 129,	 //0 7 1 
	ID_UI_SET_LCD_QUAD_1 = 130,	 //0 1 8 
	ID_UI_SET_LCD_QUAD_2 = 131,	 //0 1 8 
	ID_UI_SET_LCD_QUAD_3 = 132,	 //0 1 8 
	ID_UI_SET_LCD_QUAD_4 = 133,	 //0 1 8 
	ID_UI_SET_LED_1 = 134,	 //0 1 8 
	ID_UI_SET_LED_2 = 135,	 //0 1 8 
	ID_UI_SET_LED_3 = 136,	 //0 1 8 
	ID_UI_SET_LED_4 = 137,	 //0 1 8 
	ID_UI_SET_LED_5 = 138,	 //0 1 8 
	ID_UI_SET_LED_6 = 139,	 //0 1 8 
	ID_UI_SET_BUZZER_FREQ = 140,	 //0 1 8 
	ID_UI_SET_BUZZER_AMPL = 141,	 //0 1 8 
	ID_UI_ROLL = 142,	 //0 8 1 
	ID_UI_PITCH = 143,	 //0 8 1 
	ID_UI_YAW = 144,	 //0 8 1 
	ID_UI_ANG_RATE_X = 145,	 //0 8 1 
	ID_UI_ANG_RATE_Y = 146,	 //0 8 1 
	ID_UI_ANG_RATE_Z = 147,	 //0 8 1 
	ID_UI_BUTTONS = 148,	 //0 8 1 
	ID_UI_RC_0 = 149,	 //0 8 1 
	ID_UI_RC_1 = 150,	 //0 8 1 
	ID_UI_RC_2 = 151,	 //0 8 1 
	ID_UI_RC_3 = 152,	 //0 8 1 
	ID_UI_EXECUTION_TIME = 153,	 //0 8 1 
	ID_UI_MAX_EXECUTION_TIME = 154,	 //0 8 1 
	ID_UI_AUDIO = 155,	 //0 1 8 
	ID_UI_EMPTY_TX2 = 156,	 //0 1 8 
	ID_UI_STATUS = 157,	 //0 8 1 
	ID_UI_EMPTY_RX4 = 158,	 //0 8 1 
	ID_UI_EMPTY_RX5 = 159,	 //0 8 1 
	ID_CSR_CAN1_LOAD = 160,	 //0 2 0 
	ID_CSR_CAN2_LOAD = 161,	 //0 2 0 
	ID_CSR_CAN3_LOAD = 162,	 //0 2 0 
	ID_CSR_CAN4_LOAD = 163,	 //0 2 0 
	ID_CSR_MCU_POWER = 164,	 //0 2 0 
	ID_CSR_EMPTY_TX1 = 165,	 //0 1 2 
	ID_CSR_EMPTY_TX2 = 166,	 //0 1 2 
	ID_CSR_MCU_VOLTAGE = 167,	 //0 2 1 
	ID_CSR_MCU_CURRENT = 168,	 //0 2 1 
	ID_CSR_EMPTY_RX4 = 169,	 //0 2 1 
	ID_CSR_EMPTY_RX5 = 170,	 //0 2 1 
	ID_MB_EXECUTION_TIME = 171,	 //0 1 0 Time required to finish the schedule
	ID_ERROR_LABVIEW = 172,	 //0 1 0 Buffered errors for transmission to LabView/PC
	ID_ERROR_LCD = 173,	 //0 1 8 Buffered errors for transmission to Ranger LCD
	ID_MB_SYSTEM_INIT_FSM_STATE = 174,	 //0 1 0 System_init_fsm state number
	ID_MB_HIP_FSM_STATE = 175,	 //0 1 0 hip fsm state number
	ID_MB_FOOT_INNER_FSM_STATE = 176,	 //0 1 0 inner foot fsm state number
	ID_MB_FOOT_OUTER_FSM_STATE = 177,	 //0 1 0 outer foot fsm state number
	ID_MB_STEERING_FSM_STATE = 178,	 //0 1 0 steering fsm state number
	ID_MB_UI_FSM_STATE = 179,	 //0 1 0 ui fsm state number
	ID_MB_EMPTY_FSM1 = 180,	 //0 1 0 Unused FSM ID
	ID_MB_EMPTY_FSM2 = 181,	 //0 1 0 Unused FSM ID
	ID_MB_EMPTY_FSM3 = 182,	 //0 1 0 Unused FSM ID
	ID_E_INNER_ANG_RATE = 183,	 //0 1 0 inner leg angular rate from estimator (world frame)
	ID_E_OUTER_ANG_RATE  = 184,	 //0 1 0 outer leg angular rate from estimator (world frame)
	ID_E_INNER_ANGLE = 185,	 //0 1 0 inner leg angle from estimator (world frame)
	ID_E_OUTER_ANGLE = 186,	 //0 1 0 outer leg angle from estimator (world frame)
	ID_E_T_AFTER_HS = 187,	 //0 1 0 
	ID_E_LI_ABSANG = 188,	 //0 1 0 
	ID_E_LO_ABSANG = 189,	 //0 1 0 
	ID_E_H_RATE = 190,	 //0 1 0 estimated hip angular rate
	ID_E_FI_ABSANG = 191,	 //0 1 0 estimated inner foot absolute angle
	ID_E_FO_ABSANG = 192,	 //0 1 0 estimated outer foot absolute angle
	ID_E_SWING_F_HEIGHT = 193,	 //0 1 0 estimated swing foot height from level ground
	ID_E_LEG_STATE = 194,	 //0 1 0 estimated swing leg state
	ID_E_MIDSTANCE_LEGRATE = 195,	 //0 1 0 velocity of stance leg when robot is upright
	ID_E_MIDSTANCE_HIPRATE = 196,	 //0 1 0 velocity of hip when robot is upright (positive if robot is walking fwd)
	ID_E_MIDSTANCE_HIPANG = 197,	 //0 1 0 angle of hip when robot is upright (positive if swing leg is in front of stance leg)
	ID_E_MIDSTANCE_TIME = 198,	 //0 1 0 time for midstance measured from heelstrike
	ID_E_STEP_LEGANG = 199,	 //0 1 0 stance leg angle at heelstrike
	ID_E_STEP_LEGRATE = 200,	 //0 1 0 stance leg rate at heelstrike
	ID_E_STEP_HIPANG = 201,	 //0 1 0 hip angle at heelstrike (positive for fwd step)
	ID_E_STEP_TIME = 202,	 //0 1 0 step time
	ID_E_STEP_NO = 203,	 //0 1 0 number of steps
	ID_E_TOTAL_DISTANCE = 204,	 //0 1 0 total distance walked
	ID_E_TEST1 = 205,	 //0 1 0 dummy for testing
	ID_E_TEST2 = 206,	 //0 1 0 dummy for testing
	ID_E_TEST3 = 207,	 //0 1 0 dummy for testing
	ID_E_TEST4 = 208,	 //0 1 0 dummy for testing
	ID_E_TEST5 = 209,	 //0 1 0 dummy for testing
	ID_E_TEST6 = 210,	 //0 1 0 dummy for testing
	ID_FSM_RESET = 211,	 //0 1 0 resets the fsm so that the robot is easier to start walking
	ID_C_H_OUTER_STIFFNESS = 212,	 //1 0 1 stiffness to add in outer feet to make legs symmetric
	ID_A_H_PM_A0 = 213,	 //0 0 1 pre-mid constant current part
	ID_A_H_PM_A1 = 214,	 //0 0 1 pre-mid linear current part
	ID_C_H_PM_H_RATE = 215,	 //3 0 1 gain on velocity control
	ID_P_H_PM_H_TRATE = 216,	 //2 0 1 target hip velocity in premid
	ID_P_H_PM_TIME = 217,	 //300 0 1 time for which hip should apply a current to drive the legs forward
	ID_C_HI_SH_H_ANG = 218,	 //20 0 1 
	ID_C_HI_SH_H_RATE = 219,	 //1 0 1 
	ID_C_H_EH_H_ANG = 220,	 //40 0 1 
	ID_C_H_EH_H_RATE = 221,	 //5 0 1 
	ID_P_HI_SH_H_TANG = 222,	 //0.3 0 1 
	ID_P_H_EH_H_TANG = 223,	 //0.2 0 1 
	ID_P_H_EHOLD_ANG = 224,	 //0.2 0 1 
	ID_P_H_EH_L_TRATE = 225,	 //0.5 0 1 target legrate below which ehold should kick in
	ID_D_H_ON = 226,	 //1 0 1 hip discrete control on
	ID_DA_H_AM_A0 = 227,	 //0 1 0 value of current put in by discrete controller
	ID_DP_H_AM_H_ANG = 228,	 //0 0 1 
	ID_DC_H_AM_H_ANG = 229,	 //0 0 1 
	ID_DP_H_AM_L_ABSRATE = 230,	 //0 0 1 
	ID_DC_H_AM_L_ABSRATE = 231,	 //0 0 1 
	ID_DP_H_AM_H_RATE = 232,	 //1.2 0 1 
	ID_DC_H_AM_H_RATE = 233,	 //3 0 1 
	ID_DP_H_AM_H_DRATE = 234,	 //2.2 0 1 
	ID_DC_H_AM_H_DRATE = 235,	 //1 0 1 
	ID_H_TEST1 = 236,	 //0 0 1 dummy for testing hip
	ID_H_TEST2 = 237,	 //0 0 1 dummy for testing hip
	ID_H_TEST3 = 238,	 //0 0 1 dummy for testing hip
	ID_H_TEST4 = 239,	 //0 0 1 dummy for testing hip
	ID_H_TEST5 = 240,	 //0 0 1 dummy for testing hip
	ID_C_F_ST_F_ANG = 241,	 //4 0 1 
	ID_C_F_ST_F_RATE = 242,	 //0.2 0 1 
	ID_C_F_PP_F_ANG = 243,	 //30 0 1 
	ID_C_F_PP_F_RATE = 244,	 //3 0 1 
	ID_C_F_AP_F_ANG = 245,	 //0 0 1 
	ID_C_F_AP_F_RATE = 246,	 //0 0 1 
	ID_A_F_PP_A0 = 247,	 //3 0 1 current for prepush
	ID_C_F_FU_F_ANG = 248,	 //1 0 1 
	ID_C_F_FU_F_RATE = 249,	 //0.05 0 1 
	ID_C_F_FD_F_ANG = 250,	 //1 0 1 
	ID_C_F_FD_F_RATE = 251,	 //0.05 0 1 
	ID_C_F_SST_F_ANG = 252,	 //4 0 1 
	ID_C_F_SST_F_RATE = 253,	 //0.2 0 1 
	ID_P_F_PP_L_ABSANG = 254,	 //0.07 0 1 
	ID_P_F_AP_F_ANG = 255,	 //0 0 1 
	ID_P_F_FU_H_ANG = 256,	 //0.13 0 1 
	ID_P_F_FU_F_TANG = 257,	 //0.2 0 1 
	ID_P_F_ST_F_TANG = 258,	 //1.8 0 1 
	ID_P_F_PP_F_TANG = 259,	 //0.5 0 1 
	ID_P_F_AP_F_TANG = 260,	 //0 0 1 
	ID_P_F_FD_F_TANG = 261,	 //1.8 0 1 
	ID_P_F_SST_F_TANG = 262,	 //1.8 0 1 
	ID_D_F_ON = 263,	 //1 0 1 foot discrete control on
	ID_DA_F_PP_A0 = 264,	 //0 1 0 value of current put in by discrete controller
	ID_DP_F_PP_L_ABSRATE = 265,	 //0 0 1 
	ID_DC_F_PP_L_ABSRATE = 266,	 //0 0 1 
	ID_DP_F_PP_H_ANG = 267,	 //0 0 1 
	ID_DC_F_PP_H_ANG = 268,	 //0 0 1 
	ID_DP_F_PP_H_RATE = 269,	 //0 0 1 
	ID_DC_F_PP_H_RATE = 270,	 //0 0 1 
	ID_F_TEST1 = 271,	 //0 0 1 dummy for testing feet
	ID_F_TEST2 = 272,	 //0 0 1 dummy for testing feet
	ID_F_TEST3 = 273,	 //0 0 1 dummy for testing feet
	ID_F_TEST4 = 274,	 //0 0 1 dummy for testing feet
	ID_F_TEST5 = 275,	 //0 0 1 dummy for testing feet
	ID_F_TEST6 = 276,	 //0 0 1 dummy for testing feet
	ID_F_TEST7 = 277,	 //0 0 1 dummy for testing feet
	ID_F_TEST8 = 278,	 //0 0 1 dummy for testing feet
	ID_P_S_NULL_H_TANG = 279,	 //0.15 0 1 hip trigger angle
	ID_P_S_ILST_S_MAXANG = 280,	 //100 0 1 
	ID_P_S_ILSW_S_MAXANG = 281,	 //0 0 1 
	ID_C_S_NULL_S_ANG = 282,	 //0.002 0 1 
	ID_C_S_NULL_S_RATE = 283,	 //0 0 1 
	ID_D_S_NULL_S_DANG = 284,	 //0 1 0 desired steer angle commanded by rc
	ID_ABSOLUTE_COMP_TIME = 285,	 //0 0 1 
	ID_LV_START,	 //   
	ID_LV_CH_0,	 //   
	ID_LV_CH_1,	 //   
	ID_LV_CH_2,	 //   
	ID_LV_CH_3,	 //   
	ID_LV_CH_4,	 //   
	ID_LV_CH_5,	 //   
	ID_LV_CH_6,	 //   
	ID_LV_CH_7,	 //   
	ID_LV_CH_8,	 //   
	ID_LV_CH_9,	 //   
	ID_LV_CH_10,	 //   
	ID_LV_CH_11,	 //   
	ID_LV_CH_12,	 //   
	ID_LV_CH_13,	 //   
	ID_LV_CH_14,	 //   
	ID_LV_CH_15,	 //   
	ID_LV_CH_16,	 //   
	ID_LV_CH_17,	 //   
	ID_LV_CH_18,	 //   
	ID_LV_CH_19,	 //   
	ID_LV_CH_20,	 //   
	ID_LV_CH_21,	 //   
	ID_LV_CH_22,	 //   
	ID_LV_CH_23,	 //   
	ID_LV_CH_24,	 //   
	ID_LV_CH_25,	 //   
	ID_LV_CH_26,	 //   
	ID_LV_CH_27,	 //   
	ID_LV_CH_28,	 //   
	ID_LV_CH_29,	 //   
	ID_LV_CH_30,	 //   
	ID_LV_CH_31,	 //   
	ID_LV_CH_32,	 //   
	ID_LV_CH_33,	 //   
	ID_LV_CH_34,	 //   
	ID_LV_CH_35,	 //   
	ID_LV_CH_36,	 //   
	ID_LV_CH_37,	 //   
	ID_LV_CH_38,	 //   
	ID_LV_CH_39,	 //   
	ID_LV_CH_40,	 //   
	ID_LV_CH_41,	 //   
	ID_LV_CH_42,	 //   
	ID_LV_CH_43,	 //   
	ID_LV_CH_44,	 //   
	ID_LV_CH_45,	 //   
	ID_LV_CH_46,	 //   
	ID_LV_CH_47,	 //   
	ID_LV_VERSION,	 //   
	ID_LAST
} CAN_ID;


#endif

