#ifndef __GAITCONTROLDATA_H__
#define __GAITCONTROLDATA_H__

/* This data is automatically generated by Matlab, and is the solution to
 * a markov decision process controller design method. */
extern const float GAITDATA_WALK_ANK_PUSH[];
extern const float GAITDATA_WALK_CRIT_STANCE_ANGLE[];
extern const float GAITDATA_WALK_HIP_STEP_ANGLE[];
extern const float GAITDATA_WALK_SCISSOR_GAIN[];
extern const float GAITDATA_WALK_SCISSOR_OFFSET[];

/* These variables are used to determine which index to use */
extern const float GAITDATA_SLOPE;   
extern const float GAITDATA_CONST;
extern const int GAITDATA_NBINS;

#endif

