#include <gaitControlData.h>
 
/* This data is automatically generated by Matlab, and is the solution to
 * a markov decision process controller design method. */
const float GAITDATA_WALK_ANK_PUSH[] = { 0.98781787,  0.87034455,  0.89369037,  0.99310545,  0.91872175,  0.68055131,  0.63213298};
const float GAITDATA_WALK_CRIT_STANCE_ANGLE[] = { -0.10813772,  -0.10136705,  -0.09927470,  -0.13502895,  -0.13387048,  -0.06931960,  -0.10692148};
const float GAITDATA_WALK_HIP_STEP_ANGLE[] = { 0.21371627,  0.19545701,  0.18457254,  0.26512672,  0.28865265,  0.28723382,  0.27636845};
const float GAITDATA_WALK_SCISSOR_GAIN[] = { 1.32279616,  1.19050697,  1.42339605,  1.15582170,  1.18356595,  1.39026218,  1.19981411};
const float GAITDATA_WALK_SCISSOR_OFFSET[] = { 0.09097234,  0.08846646,  0.07363138,  0.09303052,  0.04766782,  0.09297909,  0.06793894};
 
/* These variables are used to determine which index to use */
const float GAITDATA_SLOPE =  7.95613246;
const float GAITDATA_CONST =  -0.00000000;
const int GAITDATA_NBINS = 7;
