#ifndef __GAITCONTROLDATA_H__
#define __GAITCONTROLDATA_H__
 
/* This data is automatically generated by Matlab, and is the solution to
 * a markov decision process controller design method. */
extern float GAITDATA_SPEED_KNOT_POINTS[];
extern float GAITDATA_WALK_SCISSOR_OFFSET[];
extern float GAITDATA_WALK_SCISSOR_GAIN[];
extern float GAITDATA_WALK_ANK_PUSH[];
extern float GAITDATA_WALK_CRIT_STEP_LENGTH[];
extern float GAITDATA_WALK_PUSH_INTEGRAL[];
extern int GAITDATA_NGRID;
extern float GAITDATA_TARGET_SPEED;
 
extern int GAITDATA_NBOUND;
extern float GAITDATA_LOW_BOUND[];
extern float GAITDATA_UPP_BOUND[];
 
#endif
