#include <gaitControlData.h>
 
/* This data is automatically generated by Matlab, and is the solution to
 * a markov decision process controller design method. */
int GAITDATA_NGRID = 3;
float GAITDATA_SPEED_KNOT_POINTS[] = { 0.00000000,  0.60000000,  1.00000000};
float GAITDATA_WALK_ANK_PUSH[] = { 0.99738509,  0.67937949,  0.00571354};
float GAITDATA_WALK_CRIT_STANCE_ANGLE[] = { -0.10029352,  -0.10052932,  -0.07426117};
float GAITDATA_WALK_HIP_STEP_ANGLE[] = { 0.15000000,  0.27240169,  0.30000000};
float GAITDATA_WALK_SCISSOR_GAIN[] = { 1.32111834,  1.17314492,  1.47831845};
float GAITDATA_WALK_SCISSOR_OFFSET[] = { 0.06644590,  0.09337331,  0.02637977};
