//
//CAN_ID Table for Cornell Ranger Robot
//Automatically generated by ranger_parser.m
//	 use the ranger_parser.m MATLAB script to make any changes to can_id.h, board_id.h, error_id.h, init_txlist.h, init_rxlist.h, io_data.c, error_messages.h or csr_routing_table.c
//	 the script is located in ...\SVN\Trunk\Ranger\Control\Ranger_Configuration
//

#ifndef __H_CAN_ID__
#define __H_CAN_ID__ 

typedef enum can_ids{
	ID_TIMESTAMP = 0,	 // 0 2 1 // Timestamp // time since turning on of the robot in milliseconds
	ID_ERROR_MB = 1,	 // 0 1 0 // 
	ID_ERROR_CSR = 2,	 // 0 2 1 // 
	ID_ERROR_MCH = 3,	 // 0 3 1 // 
	ID_ERROR_MCFO = 4,	 // 0 4 1 // 
	ID_ERROR_MCFI = 5,	 // 0 5 1 // 
	ID_ERROR_MCSO = 6,	 // 0 6 1 // 
	ID_ERROR_MCSI = 7,	 // 0 7 1 // 
	ID_ERROR_UI = 8,	 // 0 8 1 // 
	ID_MB_STATUS = 9,	 // 0 1 3;4;5;6;7;8;9 // 
	ID_MCH_MOTOR_VELOCITY = 10,	 // 0 3 1 // angular rate (rad/sec) of hip motor
	ID_MCH_MOTOR_CURRENT = 11,	 // 0 3 1 // hip motor current
	ID_MCH_MOTOR_POSITION = 12,	 // 0 3 1 // angle in radians of the hip motor
	ID_MCH_MOTOR_TARGET_CURRENT = 13,	 // 0 1 3 // 
	ID_MCH_ANGLE = 14,	 // 0 3 1 // angle in radians of the hip joint (difference between this and the hip motor angle is the gear back lash)
	ID_MCH_BATT_POWER = 15,	 // 0 3 1 // power consumed by the hip board. 
	ID_MCH_SHUTDOWN = 16,	 // 0 1 3 // 1 = turn off the hip motor
	ID_MCH_SLEEP = 17,	 // 0 1 3 // 
	ID_MCH_COMMAND_CURRENT = 18,	 // 0 1 3 // desired current to the hip motor = ID_MCH_COMMAND_CURRENT+ ID_MCH_STIFFNESS*hip_angle + ID_MCH_DAMPNESS*hip_angle_rate 
	ID_MCH_STIFFNESS = 19,	 // 0 1 3 // see above (ID_MCH_COMMAND_CURRENT)
	ID_MCH_DAMPNESS = 20,	 // 0 1 3 // see above (ID_MCH_COMMAND_CURRENT)
	ID_MCH_ANG_RATE = 21,	 // 0 3 1 // slightly filtered derivative of ID_MCH_ANGLE
	ID_MCH_STATUS = 22,	 // 0 3 1 // 
	ID_MCH_EXECUTION_TIME = 23,	 // 0 3 1 // time taken to execute all the functions in one row of the scheduler (software_setup.c in hip board) ( should be less than the tick time of the board; eg 0.5 ms for hip motor board)
	ID_MCH_MAX_EXECUTION_TIME = 24,	 // 0 3 1 // maximum recorded value of the ID_MCH_EXECUTION_TIME since the start of the robot
	ID_MCH_EMPTY_TX1 = 25,	 // 0 1 3 // 
	ID_MCH_EMPTY_TX2 = 26,	 // 0 1 3 // 
	ID_MCH_BATT_CURRENT = 27,	 // 0 3 1 // current in the hip board
	ID_MCH_BATT_VOLTAGE = 28,	 // 0 3 1 // 
	ID_MCH_HBRIDGE_TEMP = 29,	 // 0 3 1 // 
	ID_MCH_EMPTY_RX1 = 30,	 // 0 3 1 // 
	ID_MCH_EMPTY_RX2 = 31,	 // 0 3 1 // 
	ID_MCH_EMPTY_RX3 = 32,	 // 0 3 1 // 
	ID_MCFO_MOTOR_POSITION = 33,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_MOTOR_VELOCITY = 34,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_MOTOR_CURRENT = 35,	 // 0 4 1 // can_id for Outer Feet board-- check similar can_id; starting with MCH
	ID_MCFO_MOTOR_TARGET_CURRENT = 36,	 // 0 1 4 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_RIGHT_ANKLE_ANGLE = 37,	 // 0 4 1 // ankle joint angle in radians (zero when foot is turned all the way up)
	ID_MCFO_RIGHT_LS = 38,	 // 0 4 1 // 1 = right foot is turned all the way up
	ID_MCFO_LEFT_LS = 39,	 // 0 4 1 // 1 = left foot is turned all the way up
	ID_MCFO_RIGHT_HS = 40,	 // 0 4 1 // 1 = right foot is touching the ground; 0= foot in air
	ID_MCFO_LEFT_HS = 41,	 // 0 4 1 // 1 = left foot is touching the ground; 0= foot in air
	ID_MCFO_SHUTDOWN = 42,	 // 0 1 4 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_SLEEP = 43,	 // 0 1 4 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_BATT_POWER = 44,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_COMMAND_CURRENT = 45,	 // 0 1 4 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_STIFFNESS = 46,	 // 0 1 4 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_DAMPNESS = 47,	 // 0 1 4 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_STATUS = 48,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_LEFT_HEEL_SENSE = 49,	 // 0 4 1 // analog value from foot contact sensor (high when foot is touching the ground; low when foot is in air)
	ID_MCFO_RIGHT_HEEL_SENSE = 50,	 // 0 4 1 // analog value from foot contact sensor (high when foot is touching the ground; low when foot is in air) 
	ID_MCFO_EXECUTION_TIME = 51,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_MAX_EXECUTION_TIME = 52,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_HS_STATE = 53,	 // 0 1 4 // ??? HS means heel strike
	ID_MCFO_EMPTY_TX2 = 54,	 // 0 1 4 // 
	ID_MCFO_BATT_CURRENT = 55,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_BATT_VOLTAGE = 56,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_HBRIDGE_TEMP = 57,	 // 0 4 1 // can_id for Outer Feet board -- check similar can_id; starting with MCH
	ID_MCFO_OUTER_HS = 58,	 // 0 4 1 // ??? HS means heel strike
	ID_MCFO_RIGHT_ANKLE_RATE = 59,	 // 0 4 1 // slightly filtered derivative of the ID_MCFO_RIGHT_ANKLE_ANGLE
	ID_MCFO_EMPTY_RX3 = 60,	 // 0 4 1 // 
	ID_MCFI_MOTOR_VELOCITY = 61,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_MOTOR_CURRENT = 62,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_MOTOR_POSITION = 63,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_MOTOR_TARGET_CURRENT = 64,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_MID_ANKLE_ANGLE = 65,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_RIGHT_LS = 66,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_LEFT_LS = 67,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_RIGHT_HS = 68,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_LEFT_HS = 69,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_BATT_POWER = 70,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_SHUTDOWN = 71,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_SLEEP = 72,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_COMMAND_CURRENT = 73,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_STIFFNESS = 74,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_DAMPNESS = 75,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_STATUS = 76,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_LEFT_HEEL_SENSE = 77,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_RIGHT_HEEL_SENSE = 78,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_EXECUTION_TIME = 79,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_MAX_EXECUTION_TIME = 80,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_HS_STATE = 81,	 // 0 1 5 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_EMPTY_TX2 = 82,	 // 0 1 5 // 
	ID_MCFI_BATT_CURRENT = 83,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_BATT_VOLTAGE = 84,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_HBRIDGE_TEMP = 85,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCH
	ID_MCFI_INNER_HS = 86,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_ANKLE_RATE = 87,	 // 0 5 1 // can_id for Inner Feet board -- check similar can_id; starting with MCFO
	ID_MCFI_EMPTY_RX3 = 88,	 // 0 5 1 // 
	ID_COL_STATUS = 89,	 // 0 9 1 // IDs for the currently non existent color sensing; camera board tried on Ranger in 2010
	ID_COL_FRONT_WHITE = 90,	 // 0 9 1 // see above
	ID_COL_FRONT_RED = 91,	 // 0 9 1 // see above
	ID_COL_FRONT_GREEN = 92,	 // 0 9 1 // see above
	ID_COL_FRONT_BLUE = 93,	 // 0 9 1 // see above
	ID_COL_EXECUTION_TIME = 94,	 // 0 9 1 // see above
	ID_COL_MAX_EXECUTION_TIME = 95,	 // 0 9 1 // see above
	ID_ERROR_COL = 96,	 // 0 9 1 // see above
	ID_COL_EMPTY2 = 97,	 // 0 9 1 // see above
	ID_COL_EMPTY3 = 98,	 // 0 9 1 // see above
	ID_MCSO_LEFT_ANKLE_ANGLE = 99,	 // 0 6 1;4 // IDs for the currently non existent outer steering motor controller board tried on ranger before 2010
	ID_MCSO_LEFT_ANKLE_RATE = 100,	 // 0 6 1 // see above
	ID_MCSO_EMPTY_TX1 = 101,	 // 0 1 6 // see above
	ID_MCSO_EMPTY_TX2 = 102,	 // 0 1 6 // see above
	ID_MCSO_STATUS = 103,	 // 0 6 1 // see above
	ID_MCSO_COLOR_BACK_WHITE = 104,	 // 0 6 1 // see above
	ID_MCSO_COLOR_BACK_RED = 105,	 // 0 6 1 // see above
	ID_MCSO_COLOR_BACK_GREEN = 106,	 // 0 6 1 // see above
	ID_MCSO_COLOR_BACK_BLUE = 107,	 // 0 6 1 // see above
	ID_MCSO_EXECUTION_TIME = 108,	 // 0 6 1 // see above
	ID_MCSO_MAX_EXECUTION_TIME = 109,	 // 0 6 1 // see above
	ID_MCSI_MOTOR_CURRENT = 110,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_MOTOR_TARGET_CURRENT = 111,	 // 0 1 7 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_STEER_ANGLE = 112,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_BATT_POWER = 113,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_SHUTDOWN = 114,	 // 0 1 7 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_SLEEP = 115,	 // 0 1 7 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_COMMAND_ANG = 116,	 // 0 1 7 // steering angle commanded to the steering board
	ID_MCSI_PROP_COEFF = 117,	 // 0 1 7 // (march 2013) position coefficient in the PI controller currently used for low-level steering (in the Steering board)
	ID_MCSI_INT_COEFF = 118,	 // 0 1 7 // (march 2013) integral coefficient in the PI controller currently used for low-level steering (in the Steering board)
	ID_MCSI_STATUS = 119,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_EXECUTION_TIME = 120,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_MAX_EXECUTION_TIME = 121,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_EMPTY_TX1 = 122,	 // 0 1 7 // 
	ID_MCSI_EMPTY_TX2 = 123,	 // 0 1 7 // 
	ID_MCSI_BATT_CURRENT = 124,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_BATT_VOLTAGE = 125,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_HBRIDGE_TEMP = 126,	 // 0 7 1 // can_id for steering board -- check similar can_id; starting with MCH
	ID_MCSI_EMPTY_RX1 = 127,	 // 0 7 1 // 
	ID_MCSI_EMPTY_RX2 = 128,	 // 0 7 1 // 
	ID_MCSI_EMPTY_RX3 = 129,	 // 0 7 1 // 
	ID_UI_SET_LCD_QUAD_1 = 130,	 // 0 1 8 // data displayed in the 1st quadrant of the LCD display ????
	ID_UI_SET_LCD_QUAD_2 = 131,	 // 0 1 8 // 
	ID_UI_SET_LCD_QUAD_3 = 132,	 // 0 1 8 // 
	ID_UI_SET_LCD_QUAD_4 = 133,	 // 0 1 8 // 
	ID_UI_SET_LED_1 = 134,	 // 0 1 8 // ids for the LEDs in the UI board. 
	ID_UI_SET_LED_2 = 135,	 // 0 1 8 // 
	ID_UI_SET_LED_3 = 136,	 // 0 1 8 // 
	ID_UI_SET_LED_4 = 137,	 // 0 1 8 // 
	ID_UI_SET_LED_5 = 138,	 // 0 1 8 // 
	ID_UI_SET_LED_6 = 139,	 // 0 1 8 // 
	ID_UI_SET_BUZZER_FREQ = 140,	 // 0 1 8 // produces the sound! (used to play alma mater)
	ID_UI_SET_BUZZER_AMPL = 141,	 // 0 1 8 // produces the sound! (used to play alma mater)
	ID_UI_ROLL = 142,	 // 0 8 1 // (euler angle from imu) for-aft angle of the robot from gravity vector
	ID_UI_PITCH = 143,	 // 0 8 1 // (euler angle from imu)
	ID_UI_YAW = 144,	 // 0 8 1 // (euler angle from imu)
	ID_UI_ANG_RATE_X = 145,	 // 0 8 1 // angular velocity in rad/sec (for-aft) from imu  (see the axes marked on the imu)
	ID_UI_ANG_RATE_Y = 146,	 // 0 8 1 // imu angle rate (not exactly equal to thederivative of ID_UI_PITCH)
	ID_UI_ANG_RATE_Z = 147,	 // 0 8 1 // imu rangle rate
	ID_UI_BUTTONS = 148,	 // 0 8 1 // 
	ID_UI_RC_0 = 149,	 // 0 8 1 // most left i/o pin on the UI board (used for steering command from RC; right joystick)
	ID_UI_RC_1 = 150,	 // 0 8 1 // (used to receive signal from RC; left joystick)
	ID_UI_RC_2 = 151,	 // 0 8 1 // (used to receive signal from RC; signal coming from a knob on the right of RC transmitter; used to switch between the camera and the RC)
	ID_UI_RC_3 = 152,	 // 0 8 1 // most right i/o pin on the UI board; camera gives its output here. 
	ID_UI_EXECUTION_TIME = 153,	 // 0 8 1 // can_id for the UI board -- check similar can_id; starting with MCH
	ID_UI_MAX_EXECUTION_TIME = 154,	 // 0 8 1 // can_id for the UI board -- check similar can_id; starting with MCH
	ID_UI_AUDIO = 155,	 // 0 1 8 // 
	ID_UI_EMPTY_TX2 = 156,	 // 0 1 8 // 
	ID_UI_STATUS = 157,	 // 0 8 1 // 
	ID_UI_EMPTY_RX4 = 158,	 // 0 8 1 // 
	ID_UI_EMPTY_RX5 = 159,	 // 0 8 1 // 
	ID_CSR_CAN1_LOAD = 160,	 // 0 2 0 // 
	ID_CSR_CAN2_LOAD = 161,	 // 0 2 0 // 
	ID_CSR_CAN3_LOAD = 162,	 // 0 2 0 // 
	ID_CSR_CAN4_LOAD = 163,	 // 0 2 0 // 
	ID_CSR_MCU_POWER = 164,	 // 0 2 0 // 
	ID_CSR_EMPTY_TX1 = 165,	 // 0 1 2 // 
	ID_CSR_EMPTY_TX2 = 166,	 // 0 1 2 // 
	ID_CSR_MCU_VOLTAGE = 167,	 // 0 2 1 // 
	ID_CSR_MCU_CURRENT = 168,	 // 0 2 1 // 
	ID_CSR_EMPTY_RX4 = 169,	 // 0 2 1 // 
	ID_CSR_EMPTY_RX5 = 170,	 // 0 2 1 // 
	ID_MB_EXECUTION_TIME = 171,	 // 0 1 0 // Time required to finish the schedule
	ID_ERROR_LABVIEW = 172,	 // 0 1 0 // Buffered errors for transmission to LabView/PC
	ID_ERROR_LCD = 173,	 // 0 1 8 // Buffered errors for transmission to Ranger LCD
	ID_MB_SYSTEM_INIT_FSM_STATE = 174,	 // 0 1 0 // System_init_fsm state number
	ID_MB_HIP_FSM_STATE = 175,	 // 0 1 0 // hip fsm state number
	ID_MB_FOOT_INNER_FSM_STATE = 176,	 // 0 1 0 // inner foot fsm state number
	ID_MB_FOOT_OUTER_FSM_STATE = 177,	 // 0 1 0 // outer foot fsm state number
	ID_MB_STEERING_FSM_STATE = 178,	 // 0 1 0 // steering fsm state number
	ID_MB_UI_FSM_STATE = 179,	 // 0 1 0 // ui fsm state number
	ID_MB_TOP_FSM_STATE = 180,	 // 0 1 0 // top fsm state number
	ID_MB_LEG_FSM_STATE = 181,	 // 0 1 0 // leg fsm state
	ID_MB_ROCK_HIP_FSM_STATE = 182,	 // 0 1 0 // rock hip fsm state
	ID_MB_ROCK_FI_FSM_STATE = 183,	 // 0 1 0 // rock foot inner fsm state
	ID_MB_ROCK_FO_FSM_STATE = 184,	 // 0 1 0 // rock foot outer fsm state
	ID_MB_EMPTY_FSM3 = 185,	 // 0 1 0 // Unused FSM ID
	ID_E_MCH_MOTOR_VELOCITY = 186,	 // 0 1 0 // estimated angular rate (rad/sec) of hip motor
	ID_E_MCH_ANG_RATE = 187,	 // 0 1 0 // estimated slightly filtered derivative of ID_MCH_ANGLE
	ID_E_INNER_ANG_RATE = 188,	 // 0 1 0 // inner leg angular rate from estimator (world frame) rad/s; positive if falling forward
	ID_E_OUTER_ANG_RATE  = 189,	 // 0 1 0 // outer leg angle from estimator (world frame); rad; measured from vertical; positive if leaning forward
	ID_E_INNER_ANGLE = 190,	 // 0 1 0 // not being used (it's free)
	ID_E_OUTER_ANGLE = 191,	 // 0 1 0 // not being used (it's free)
	ID_E_T_AFTER_HS = 192,	 // 0 1 0 // time in ms since the last Heel strike
	ID_E_LI_ABSANG = 193,	 // 0 1 0 // inner leg angle from estimator (world frame); rad; measured from vertical; positive if leaning forward
	ID_E_LO_ABSANG = 194,	 // 0 1 0 // outer leg angle from estimator (world frame); rad; measured from vertical; positive if leaning forward
	ID_E_H_RATE = 195,	 // 0 1 0 // estimated hip angular rate  (filtered version of ID_MCH_ANG_RATE)
	ID_E_FI_ABSANG = 196,	 // 0 1 0 // estimated inner foot absolute angle; rad; not measured from vertical; positive if turned forward
	ID_E_FO_ABSANG = 197,	 // 0 1 0 // estimated outer foot absolute angle; rad; not measured from vertical; positive if turned forward
	ID_E_SWING_F_HEIGHT = 198,	 // 0 1 0 // estimated swing foot height from level ground
	ID_E_LEG_STATE = 199,	 // 0 1 0 // estimated swing leg state
	ID_E_MIDSTANCE_LEGRATE = 200,	 // 0 1 0 // velocity of stance leg when robot is upright
	ID_E_MIDSTANCE_HIPRATE = 201,	 // 0 1 0 // velocity of hip when robot is upright (positive if robot is walking fwd)
	ID_E_MIDSTANCE_HIPANG = 202,	 // 0 1 0 // angle of hip when robot is upright (positive if swing leg is in front of stance leg)
	ID_E_MIDSTANCE_TIME = 203,	 // 0 1 0 // time for midstance measured from heelstrike
	ID_E_STEP_LEGANG = 204,	 // 0 1 0 // stance leg angle at heelstrike
	ID_E_STEP_LEGRATE = 205,	 // 0 1 0 // stance leg rate at heelstrike
	ID_E_STEP_HIPANG = 206,	 // 0 1 0 // hip angle at heelstrike (positive for fwd step)
	ID_E_STEP_TIME = 207,	 // 0 1 0 // step time
	ID_E_STEP_NO = 208,	 // 0 1 0 // number of steps since the start (of entering the walk state in the ui_fsm)
	ID_E_TOTAL_DISTANCE = 209,	 // 0 1 0 // total distance walked since the start in meters
	ID_E_SS0_LEGANG = 210,	 // 0 1 0 // leg angle at beginning of swing phase
	ID_E_SS0_LEGRATE = 211,	 // 0 1 0 // leg rate at beginning of swing phase
	ID_E_H_MOTOR_RATE = 212,	 // 0 1 0 // hip motor rate; filtered version of ID_MCH_MOTOR_VELOCITY
	ID_E_EXEC_TIME = 213,	 // 0 1 0 // time taken by estimator to run
	ID_E_INT_LO_ABSANG_RESET = 214,	 // 0 1 0 // outer foot reset at hs
	ID_E_TIME_TO_HS = 215,	 // 0 1 0 // estimated time for next hs to happen (not tested/functioning)
	ID_E_SLOPE = 216,	 // 0 1 0 // estimated ground slope (not tested/ functioning)
	ID_E_SWING_LEG = 217,	 // 0 1 0 // 0 = outer leg is in swing; 1 = inner leg is in swing
	ID_E_F_PP_MISSED = 218,	 // 0 1 0 // 0 for outer and 1 for inner prepush missed
	ID_E_F_PP2HS_TIME = 219,	 // 0 1 0 // prepush to heelstrike time
	ID_E_F_PP_TIME = 220,	 // 0 1 0 // prepush time in ms
	ID_E_F_AP_TIME = 221,	 // 0 1 0 // afterpush time in ms
	ID_E_H_PS_TIME = 222,	 // 0 1 0 // pre-swing time in ms
	ID_E_H_AM_TIME = 223,	 // 0 1 0 // pre-swing time in ms
	ID_E_ANK2ANK_HT = 224,	 // 0 1 0 // height of swing ankle with respect to the stance ankle (meters)
	ID_E_DBL_STANCE = 225,	 // 0 1 0 // estimation of double/single stance state: 1 = in double stance; 0 = in single stance
	ID_E_TEST3 = 226,	 // 0 1 0 // dummy for testing
	ID_E_TEST4 = 227,	 // 0 1 0 // dummy for testing
	ID_E_TEST5 = 228,	 // 0 1 0 // dummy for testing
	ID_E_TEST6 = 229,	 // 0 1 0 // dummy for testing
	ID_E_TEST7 = 230,	 // 0 1 0 // dummy for testing
	ID_E_TEST8 = 231,	 // 0 1 0 // dummy for testing
	ID_E_TEST9 = 232,	 // 0 1 0 // dummy for testing
	ID_E_TEST10 = 233,	 // 0 1 0 // dummy for testing
	ID_E_TEST11 = 234,	 // 0 1 0 // dummy for testing
	ID_E_TEST12 = 235,	 // 0 1 0 // dummy for testing
	ID_CTRL_TEST_R0 = 236,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R1 = 237,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R2 = 238,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R3 = 239,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R4 = 240,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R5 = 241,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R6 = 242,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R7 = 243,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R8 = 244,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_R9 = 245,	 // 0 0 1 // test read from labview
	ID_CTRL_TEST_W0 = 246,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W1 = 247,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W2 = 248,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W3 = 249,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W4 = 250,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W5 = 251,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W6 = 252,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W7 = 253,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W8 = 254,	 // 0 1 0 // test write to labview
	ID_CTRL_TEST_W9 = 255,	 // 0 1 0 // test write to labview
	ID_EST_TEST_R0 = 256,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R1 = 257,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R2 = 258,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R3 = 259,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R4 = 260,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R5 = 261,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R6 = 262,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R7 = 263,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R8 = 264,	 // 0 0 1 // test read from labview
	ID_EST_TEST_R9 = 265,	 // 0 0 1 // test read from labview
	ID_EST_TEST_W0 = 266,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W1 = 267,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W2 = 268,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W3 = 269,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W4 = 270,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W5 = 271,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W6 = 272,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W7 = 273,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W8 = 274,	 // 0 1 0 // test write to labview
	ID_EST_TEST_W9 = 275,	 // 0 1 0 // test write to labview
	ID_LV_START,	 //    // 
	ID_LV_CH_0,	 //    // 
	ID_LV_CH_1,	 //    // 
	ID_LV_CH_2,	 //    // 
	ID_LV_CH_3,	 //    // 
	ID_LV_CH_4,	 //    // 
	ID_LV_CH_5,	 //    // 
	ID_LV_CH_6,	 //    // 
	ID_LV_CH_7,	 //    // 
	ID_LV_CH_8,	 //    // 
	ID_LV_CH_9,	 //    // 
	ID_LV_CH_10,	 //    // 
	ID_LV_CH_11,	 //    // 
	ID_LV_CH_12,	 //    // 
	ID_LV_CH_13,	 //    // 
	ID_LV_CH_14,	 //    // 
	ID_LV_CH_15,	 //    // 
	ID_LV_CH_16,	 //    // 
	ID_LV_CH_17,	 //    // 
	ID_LV_CH_18,	 //    // 
	ID_LV_CH_19,	 //    // 
	ID_LV_CH_20,	 //    // 
	ID_LV_CH_21,	 //    // 
	ID_LV_CH_22,	 //    // 
	ID_LV_CH_23,	 //    // 
	ID_LV_CH_24,	 //    // 
	ID_LV_CH_25,	 //    // 
	ID_LV_CH_26,	 //    // 
	ID_LV_CH_27,	 //    // 
	ID_LV_CH_28,	 //    // 
	ID_LV_CH_29,	 //    // 
	ID_LV_CH_30,	 //    // 
	ID_LV_CH_31,	 //    // 
	ID_LV_CH_32,	 //    // 
	ID_LV_CH_33,	 //    // 
	ID_LV_CH_34,	 //    // 
	ID_LV_CH_35,	 //    // 
	ID_LV_CH_36,	 //    // 
	ID_LV_CH_37,	 //    // 
	ID_LV_CH_38,	 //    // 
	ID_LV_CH_39,	 //    // 
	ID_LV_CH_40,	 //    // 
	ID_LV_CH_41,	 //    // 
	ID_LV_CH_42,	 //    // 
	ID_LV_CH_43,	 //    // 
	ID_LV_CH_44,	 //    // 
	ID_LV_CH_45,	 //    // 
	ID_LV_CH_46,	 //    // 
	ID_LV_CH_47,	 //    // 
	ID_LV_VERSION,	 //    // 
	ID_LAST
} CAN_ID;


#endif

