//
//CAN_ID Table for Cornell Ranger Robot
//Automatically generated by file_read.m
//

#ifndef __H_CAN_ID__
#define __H_CAN_ID__ 

typedef enum can_ids{
	ID_TIMESTAMP = 0,	 //0 2 1 Timestamp
	ID_ERROR_MB = 1,	 //0 1 0 
	ID_ERROR_CSR = 2,	 //0 2 1 
	ID_ERROR_MCH = 3,	 //0 3 1 
	ID_ERROR_MCFO = 4,	 //0 4 1 
	ID_ERROR_MCFI = 5,	 //0 5 1 
	ID_ERROR_MCSO = 6,	 //0 6 1 
	ID_ERROR_MCSI = 7,	 //0 7 1 
	ID_ERROR_UI = 8,	 //0 8 1 
	ID_MB_STATUS = 9,	 //0 1 3;4;5;6;7;8;9 
	ID_MCH_MOTOR_VELOCITY = 10,	 //0 3 1 
	ID_MCH_MOTOR_CURRENT = 11,	 //0 3 1 
	ID_MCH_MOTOR_POSITION = 12,	 //0 3 1 
	ID_MCH_MOTOR_TARGET_CURRENT = 13,	 //0 1 3 
	ID_MCH_ANGLE = 14,	 //0 3 1 
	ID_MCH_BATT_POWER = 15,	 //0 3 1 
	ID_MCH_SHUTDOWN = 16,	 //0 1 3 
	ID_MCH_SLEEP = 17,	 //0 1 3 
	ID_MCH_COMMAND_CURRENT = 18,	 //0 1 3 
	ID_MCH_STIFFNESS = 19,	 //0 1 3 
	ID_MCH_DAMPNESS = 20,	 //0 1 3 
	ID_MCH_ANG_RATE = 21,	 //0 3 1 
	ID_MCH_STATUS = 22,	 //0 3 1 
	ID_MCH_EXECUTION_TIME = 23,	 //0 3 1 
	ID_MCH_MAX_EXECUTION_TIME = 24,	 //0 3 1 
	ID_MCH_EMPTY_TX1 = 25,	 //0 1 3 
	ID_MCH_EMPTY_TX2 = 26,	 //0 1 3 
	ID_MCH_BATT_CURRENT = 27,	 //0 3 1 
	ID_MCH_BATT_VOLTAGE = 28,	 //0 3 1 
	ID_MCH_HBRIDGE_TEMP = 29,	 //0 3 1 
	ID_MCH_EMPTY_RX1 = 30,	 //0 3 1 
	ID_MCH_EMPTY_RX2 = 31,	 //0 3 1 
	ID_MCH_EMPTY_RX3 = 32,	 //0 3 1 
	ID_MCFO_MOTOR_POSITION = 33,	 //0 4 1 
	ID_MCFO_MOTOR_VELOCITY = 34,	 //0 4 1 
	ID_MCFO_MOTOR_CURRENT = 35,	 //0 4 1 
	ID_MCFO_MOTOR_TARGET_CURRENT = 36,	 //0 1 4 
	ID_MCFO_RIGHT_ANKLE_ANGLE = 37,	 //0 4 1 
	ID_MCFO_RIGHT_LS = 38,	 //0 4 1 
	ID_MCFO_LEFT_LS = 39,	 //0 4 1 
	ID_MCFO_RIGHT_HS = 40,	 //0 4 1 
	ID_MCFO_LEFT_HS = 41,	 //0 4 1 
	ID_MCFO_SHUTDOWN = 42,	 //0 1 4 
	ID_MCFO_SLEEP = 43,	 //0 1 4 
	ID_MCFO_BATT_POWER = 44,	 //0 4 1 
	ID_MCFO_COMMAND_CURRENT = 45,	 //0 1 4 
	ID_MCFO_STIFFNESS = 46,	 //0 1 4 
	ID_MCFO_DAMPNESS = 47,	 //0 1 4 
	ID_MCFO_STATUS = 48,	 //0 4 1 
	ID_MCFO_LEFT_HEEL_SENSE = 49,	 //0 4 1 
	ID_MCFO_RIGHT_HEEL_SENSE = 50,	 //0 4 1 
	ID_MCFO_EXECUTION_TIME = 51,	 //0 4 1 
	ID_MCFO_MAX_EXECUTION_TIME = 52,	 //0 4 1 
	ID_MCFO_HS_STATE = 53,	 //0 1 4 
	ID_MCFO_EMPTY_TX2 = 54,	 //0 1 4 
	ID_MCFO_BATT_CURRENT = 55,	 //0 4 1 
	ID_MCFO_BATT_VOLTAGE = 56,	 //0 4 1 
	ID_MCFO_HBRIDGE_TEMP = 57,	 //0 4 1 
	ID_MCFO_OUTER_HS = 58,	 //0 4 1 
	ID_MCFO_RIGHT_ANKLE_RATE = 59,	 //0 4 1 
	ID_MCFO_EMPTY_RX3 = 60,	 //0 4 1 
	ID_MCFI_MOTOR_VELOCITY = 61,	 //0 5 1 
	ID_MCFI_MOTOR_CURRENT = 62,	 //0 5 1 
	ID_MCFI_MOTOR_POSITION = 63,	 //0 5 1 
	ID_MCFI_MOTOR_TARGET_CURRENT = 64,	 //0 1 5 
	ID_MCFI_MID_ANKLE_ANGLE = 65,	 //0 5 1 
	ID_MCFI_RIGHT_LS = 66,	 //0 5 1 
	ID_MCFI_LEFT_LS = 67,	 //0 5 1 
	ID_MCFI_RIGHT_HS = 68,	 //0 5 1 
	ID_MCFI_LEFT_HS = 69,	 //0 5 1 
	ID_MCFI_BATT_POWER = 70,	 //0 5 1 
	ID_MCFI_SHUTDOWN = 71,	 //0 1 5 
	ID_MCFI_SLEEP = 72,	 //0 1 5 
	ID_MCFI_COMMAND_CURRENT = 73,	 //0 1 5 
	ID_MCFI_STIFFNESS = 74,	 //0 1 5 
	ID_MCFI_DAMPNESS = 75,	 //0 1 5 
	ID_MCFI_STATUS = 76,	 //0 5 1 
	ID_MCFI_LEFT_HEEL_SENSE = 77,	 //0 5 1 
	ID_MCFI_RIGHT_HEEL_SENSE = 78,	 //0 5 1 
	ID_MCFI_EXECUTION_TIME = 79,	 //0 5 1 
	ID_MCFI_MAX_EXECUTION_TIME = 80,	 //0 5 1 
	ID_MCFI_HS_STATE = 81,	 //0 1 5 
	ID_MCFI_EMPTY_TX2 = 82,	 //0 1 5 
	ID_MCFI_BATT_CURRENT = 83,	 //0 5 1 
	ID_MCFI_BATT_VOLTAGE = 84,	 //0 5 1 
	ID_MCFI_HBRIDGE_TEMP = 85,	 //0 5 1 
	ID_MCFI_INNER_HS = 86,	 //0 5 1 
	ID_MCFI_ANKLE_RATE = 87,	 //0 5 1 
	ID_MCFI_EMPTY_RX3 = 88,	 //0 5 1 
	ID_COL_STATUS = 89,	 //0 9 1 
	ID_COL_FRONT_WHITE = 90,	 //0 9 1 
	ID_COL_FRONT_RED = 91,	 //0 9 1 
	ID_COL_FRONT_GREEN = 92,	 //0 9 1 
	ID_COL_FRONT_BLUE = 93,	 //0 9 1 
	ID_COL_EXECUTION_TIME = 94,	 //0 9 1 
	ID_COL_MAX_EXECUTION_TIME = 95,	 //0 9 1 
	ID_ERROR_COL = 96,	 //0 9 1 
	ID_COL_EMPTY2 = 97,	 //0 9 1 
	ID_COL_EMPTY3 = 98,	 //0 9 1 
	ID_MCSO_LEFT_ANKLE_ANGLE = 99,	 //0 6 1;4 
	ID_MCSO_LEFT_ANKLE_RATE = 100,	 //0 6 1 
	ID_MCSO_EMPTY_TX1 = 101,	 //0 1 6 
	ID_MCSO_EMPTY_TX2 = 102,	 //0 1 6 
	ID_MCSO_STATUS = 103,	 //0 6 1 
	ID_MCSO_COLOR_BACK_WHITE = 104,	 //0 6 1 
	ID_MCSO_COLOR_BACK_RED = 105,	 //0 6 1 
	ID_MCSO_COLOR_BACK_GREEN = 106,	 //0 6 1 
	ID_MCSO_COLOR_BACK_BLUE = 107,	 //0 6 1 
	ID_MCSO_EXECUTION_TIME = 108,	 //0 6 1 
	ID_MCSO_MAX_EXECUTION_TIME = 109,	 //0 6 1 
	ID_MCSI_MOTOR_CURRENT = 110,	 //0 7 1 
	ID_MCSI_MOTOR_TARGET_CURRENT = 111,	 //0 1 7 
	ID_MCSI_STEER_ANGLE = 112,	 //0 7 1 
	ID_MCSI_BATT_POWER = 113,	 //0 7 1 
	ID_MCSI_SHUTDOWN = 114,	 //0 1 7 
	ID_MCSI_SLEEP = 115,	 //0 1 7 
	ID_MCSI_COMMAND_CURRENT = 116,	 //0 1 7 
	ID_MCSI_STIFFNESS = 117,	 //0 1 7 
	ID_MCSI_DAMPNESS = 118,	 //0 1 7 
	ID_MCSI_STATUS = 119,	 //0 7 1 
	ID_MCSI_EXECUTION_TIME = 120,	 //0 7 1 
	ID_MCSI_MAX_EXECUTION_TIME = 121,	 //0 7 1 
	ID_MCSI_EMPTY_TX1 = 122,	 //0 1 7 
	ID_MCSI_EMPTY_TX2 = 123,	 //0 1 7 
	ID_MCSI_BATT_CURRENT = 124,	 //0 7 1 
	ID_MCSI_BATT_VOLTAGE = 125,	 //0 7 1 
	ID_MCSI_HBRIDGE_TEMP = 126,	 //0 7 1 
	ID_MCSI_EMPTY_RX1 = 127,	 //0 7 1 
	ID_MCSI_EMPTY_RX2 = 128,	 //0 7 1 
	ID_MCSI_EMPTY_RX3 = 129,	 //0 7 1 
	ID_UI_SET_LCD_QUAD_1 = 130,	 //0 1 8 
	ID_UI_SET_LCD_QUAD_2 = 131,	 //0 1 8 
	ID_UI_SET_LCD_QUAD_3 = 132,	 //0 1 8 
	ID_UI_SET_LCD_QUAD_4 = 133,	 //0 1 8 
	ID_UI_SET_LED_1 = 134,	 //0 1 8 
	ID_UI_SET_LED_2 = 135,	 //0 1 8 
	ID_UI_SET_LED_3 = 136,	 //0 1 8 
	ID_UI_SET_LED_4 = 137,	 //0 1 8 
	ID_UI_SET_LED_5 = 138,	 //0 1 8 
	ID_UI_SET_LED_6 = 139,	 //0 1 8 
	ID_UI_SET_BUZZER_FREQ = 140,	 //0 1 8 
	ID_UI_SET_BUZZER_AMPL = 141,	 //0 1 8 
	ID_UI_ROLL = 142,	 //0 8 1 
	ID_UI_PITCH = 143,	 //0 8 1 
	ID_UI_YAW = 144,	 //0 8 1 
	ID_UI_ANG_RATE_X = 145,	 //0 8 1 
	ID_UI_ANG_RATE_Y = 146,	 //0 8 1 
	ID_UI_ANG_RATE_Z = 147,	 //0 8 1 
	ID_UI_BUTTONS = 148,	 //0 8 1 
	ID_UI_RC_0 = 149,	 //0 8 1 
	ID_UI_RC_1 = 150,	 //0 8 1 
	ID_UI_RC_2 = 151,	 //0 8 1 
	ID_UI_RC_3 = 152,	 //0 8 1 
	ID_UI_EXECUTION_TIME = 153,	 //0 8 1 
	ID_UI_MAX_EXECUTION_TIME = 154,	 //0 8 1 
	ID_UI_AUDIO = 155,	 //0 1 8 
	ID_UI_EMPTY_TX2 = 156,	 //0 1 8 
	ID_UI_STATUS = 157,	 //0 8 1 
	ID_UI_EMPTY_RX4 = 158,	 //0 8 1 
	ID_UI_EMPTY_RX5 = 159,	 //0 8 1 
	ID_CSR_CAN1_LOAD = 160,	 //0 2 0 
	ID_CSR_CAN2_LOAD = 161,	 //0 2 0 
	ID_CSR_CAN3_LOAD = 162,	 //0 2 0 
	ID_CSR_CAN4_LOAD = 163,	 //0 2 0 
	ID_CSR_MCU_POWER = 164,	 //0 2 0 
	ID_CSR_EMPTY_TX1 = 165,	 //0 1 2 
	ID_CSR_EMPTY_TX2 = 166,	 //0 1 2 
	ID_CSR_MCU_VOLTAGE = 167,	 //0 2 1 
	ID_CSR_MCU_CURRENT = 168,	 //0 2 1 
	ID_CSR_EMPTY_RX4 = 169,	 //0 2 1 
	ID_CSR_EMPTY_RX5 = 170,	 //0 2 1 
	ID_MB_EXECUTION_TIME = 171,	 //0 1 0 Time required to finish the schedule
	ID_ERROR_LABVIEW = 172,	 //0 1 0 Buffered errors for transmission to LabView/PC
	ID_ERROR_LCD = 173,	 //0 1 8 Buffered errors for transmission to Ranger LCD
	ID_MB_SYSTEM_INIT_FSM_STATE = 174,	 //0 1 0 System_init_fsm state number
	ID_MB_HIP_FSM_STATE = 175,	 //0 1 0 hip fsm state number
	ID_MB_FOOT_INNER_FSM_STATE = 176,	 //0 1 0 inner foot fsm state number
	ID_MB_FOOT_OUTER_FSM_STATE = 177,	 //0 1 0 outer foot fsm state number
	ID_MB_STEERING_FSM_STATE = 178,	 //0 1 0 steering fsm state number
	ID_MB_UI_FSM_STATE = 179,	 //0 1 0 ui fsm state number
	ID_MB_TOP_FSM_STATE = 180,	 //0 1 0 top fsm state number
	ID_MB_LEG_FSM_STATE = 181,	 //0 1 0 leg fsm state
	ID_MB_EMPTY_FSM3 = 182,	 //0 1 0 Unused FSM ID
	ID_E_INNER_ANG_RATE = 183,	 //0 1 0 inner leg angular rate from estimator (world frame)
	ID_E_OUTER_ANG_RATE  = 184,	 //0 1 0 outer leg angular rate from estimator (world frame)
	ID_E_INNER_ANGLE = 185,	 //0 1 0 inner leg angle from estimator (world frame)
	ID_E_OUTER_ANGLE = 186,	 //0 1 0 outer leg angle from estimator (world frame)
	ID_E_T_AFTER_HS = 187,	 //0 1 0 
	ID_E_LI_ABSANG = 188,	 //0 1 0 
	ID_E_LO_ABSANG = 189,	 //0 1 0 
	ID_E_H_RATE = 190,	 //0 1 0 estimated hip angular rate
	ID_E_FI_ABSANG = 191,	 //0 1 0 estimated inner foot absolute angle
	ID_E_FO_ABSANG = 192,	 //0 1 0 estimated outer foot absolute angle
	ID_E_SWING_F_HEIGHT = 193,	 //0 1 0 estimated swing foot height from level ground
	ID_E_LEG_STATE = 194,	 //0 1 0 estimated swing leg state
	ID_E_MIDSTANCE_LEGRATE = 195,	 //0 1 0 velocity of stance leg when robot is upright
	ID_E_MIDSTANCE_HIPRATE = 196,	 //0 1 0 velocity of hip when robot is upright (positive if robot is walking fwd)
	ID_E_MIDSTANCE_HIPANG = 197,	 //0 1 0 angle of hip when robot is upright (positive if swing leg is in front of stance leg)
	ID_E_MIDSTANCE_TIME = 198,	 //0 1 0 time for midstance measured from heelstrike
	ID_E_STEP_LEGANG = 199,	 //0 1 0 stance leg angle at heelstrike
	ID_E_STEP_LEGRATE = 200,	 //0 1 0 stance leg rate at heelstrike
	ID_E_STEP_HIPANG = 201,	 //0 1 0 hip angle at heelstrike (positive for fwd step)
	ID_E_STEP_TIME = 202,	 //0 1 0 step time
	ID_E_STEP_NO = 203,	 //0 1 0 number of steps
	ID_E_TOTAL_DISTANCE = 204,	 //0 1 0 total distance walked
	ID_E_SS0_LEGANG = 205,	 //0 1 0 leg angle at beginning of swing phase
	ID_E_SS0_LEGRATE = 206,	 //0 1 0 leg rate at beginning of swing phase
	ID_E_H_MOTOR_RATE = 207,	 //0 1 0 motor rate
	ID_E_EXEC_TIME = 208,	 //0 1 0 time taken by estimator
	ID_E_INT_LO_ABSANG_RESET = 209,	 //0 1 0 outer foot reset at hs
	ID_E_TIME_TO_HS = 210,	 //0 1 0 estimated time to hs
	ID_E_SLOPE = 211,	 //0 1 0 estimated ground slope
	ID_E_SWING_LEG = 212,	 //0 1 0 0 for outer and 1 for inner
	ID_E_F_PP_MISSED = 213,	 //0 1 0 0 for outer and 1 for inner prepush missed
	ID_E_F_PP2HS_TIME = 214,	 //0 1 0 prepush to heelstrike time
	ID_E_F_PP_TIME = 215,	 //0 1 0 prepush time in ms
	ID_E_F_AP_TIME = 216,	 //0 1 0 afterpush time in ms
	ID_E_H_PS_TIME = 217,	 //0 1 0 pre-swing time in ms
	ID_E_H_AM_TIME = 218,	 //0 1 0 pre-swing time in ms
	ID_E_ANK2ANK_HT = 219,	 //0 1 0 dummy for testing
	ID_E_TEST2 = 220,	 //0 1 0 dummy for testing
	ID_E_TEST3 = 221,	 //0 1 0 dummy for testing
	ID_E_TEST4 = 222,	 //0 1 0 dummy for testing
	ID_E_TEST5 = 223,	 //0 1 0 dummy for testing
	ID_E_TEST6 = 224,	 //0 1 0 dummy for testing
	ID_E_TEST7 = 225,	 //0 1 0 dummy for testing
	ID_E_TEST8 = 226,	 //0 1 0 dummy for testing
	ID_E_TEST9 = 227,	 //0 1 0 dummy for testing
	ID_E_TEST10 = 228,	 //0 1 0 dummy for testing
	ID_E_TEST11 = 229,	 //0 1 0 dummy for testing
	ID_E_TEST12 = 230,	 //0 1 0 dummy for testing
	ID_FSM_RESET = 231,	 //0 1 0 resets the fsm so that the robot is easier to start walking
	ID_C_H_OUTER_STIFFNESS = 232,	 //2 0 1 stiffness to add in outer feet to make legs symmetric (was 1)
	ID_C_H_OUTER_DAMPNESS = 233,	 //0 0 1 dampness to add in outer feet to make legs symmetric 
	ID_A_H_PM_A0 = 234,	 //0 0 1 pre-mid constant current part
	ID_A_H_PM_A1 = 235,	 //0 0 1 pre-mid linear current part not used
	ID_C_H_PM_H_RATE = 236,	 //3 0 1 gain on velocity control
	ID_P_H_PM_H_TRATE = 237,	 //2 0 1 target hip velocity in premid
	ID_P_H_PM_TIME = 238,	 //300 0 1 not used
	ID_C_HI_SH_H_ANG = 239,	 //30 0 1 
	ID_C_HI_SH_H_RATE = 240,	 //3 0 1 
	ID_C_H_EH_H_ANG = 241,	 //30 0 1 
	ID_C_H_EH_H_RATE = 242,	 //4 0 1 
	ID_P_HI_SH_H_TANG = 243,	 //0.35 0 1 
	ID_P_H_EH_H_TANG = 244,	 //0.35 0 1 
	ID_P_H_EHOLD_ANG = 245,	 //0.2 0 1 
	ID_P_H_EHOLD_ANG2 = 246,	 //0.3 0 1 
	ID_P_H_EH_L_TRATE = 247,	 //0.4 0 1 target legrate below which ehold should kick in (was 0.5)
	ID_P_H_EH_L_TANG = 248,	 //0.2 0 1 target mid-stance angle for ehold
	ID_P_H_PM_F_ANG = 249,	 //0 0 1 feet absolute angle before pre-mid starts
	ID_P_H_PM_F_RATE = 250,	 //5 0 1 ankle swing rate before pre-mid starts
	ID_D_H_ON = 251,	 //1 0 1 after-mid discrete controller
	ID_DA_H_AM_A1 = 252,	 //0 1 0 value of current put in by discrete controller
	ID_DA_H_AM_A2 = 253,	 //0 1 0 value of current put in by discrete controller
	ID_DA2_H_AM_H_ANG1 = 254,	 //0 1 0 
	ID_DA2_H_AM_H_ANG2 = 255,	 //0 1 0 
	ID_DA2_H_AM_H_RATE1 = 256,	 //0 1 0 
	ID_DA2_H_AM_H_RATE2 = 257,	 //0 1 0 
	ID_DA3_H_AM_H_ANG1 = 258,	 //0 1 0 
	ID_DA3_H_AM_H_ANG2 = 259,	 //0 1 0 
	ID_DA3_H_AM_L_ABSRATE1 = 260,	 //0 1 0 
	ID_DA3_H_AM_L_ABSRATE2 = 261,	 //0 1 0 
	ID_DA3_H_AM_H_RATE1 = 262,	 //0 1 0 
	ID_DA3_H_AM_H_RATE2 = 263,	 //0 1 0 
	ID_DP_H_AM_H_ANG = 264,	 //0 0 1 
	ID_DP_H_AM_L_ABSRATE = 265,	 //0.72 0 1 
	ID_DP_H_AM_H_RATE = 266,	 //1.66 0 1 
	ID_DP_H_AM_H_DRATE = 267,	 //2.3 0 1 
	ID_DC_H_AM_H_ANG = 268,	 //1 0 1 
	ID_DC_H_AM_L_ABSRATE = 269,	 //0 0 1 
	ID_DC_H_AM_H_RATE = 270,	 //1 0 1 
	ID_DC_H_AM_H_DRATE = 271,	 //2 0 1 
	ID_DP_H_AM_TIME1 = 272,	 //150 0 1 time 1 for discrete control
	ID_DP_H_AM_TIME2 = 273,	 //300 0 1 time 2 for discrete control
	ID_DC2_H_AM_H_ANG1 = 274,	 //-1 0 1 
	ID_DC2_H_AM_H_ANG2 = 275,	 //-0.5 0 1 
	ID_DC2_H_AM_H_RATE1 = 276,	 //-0.3 0 1 
	ID_DC2_H_AM_H_RATE2 = 277,	 //-0.2 0 1 
	ID_DC3_H_AM_H_ANG1 = 278,	 //2 0 1 
	ID_DC3_H_AM_H_ANG2 = 279,	 //1 0 1 
	ID_DC3_H_AM_L_ABSRATE1 = 280,	 //0 0 1 
	ID_DC3_H_AM_L_ABSRATE2 = 281,	 //0 0 1 
	ID_DC3_H_AM_H_RATE1 = 282,	 //0 0 1 
	ID_DC3_H_AM_H_RATE2 = 283,	 //0 0 1 
	ID_D_H2_ON = 284,	 //0 0 1 ss0 discrete controller
	ID_DA_H_PM_A1 = 285,	 //0 1 0 value of current put in by discrete controller
	ID_DA_H_PM_A2 = 286,	 //0 1 0 value of current put in by discrete controller
	ID_DA_H_PM_L_ABSANG1 = 287,	 //0 1 0 
	ID_DA_H_PM_L_ABSANG2 = 288,	 //0 1 0 
	ID_DA_H_PM_L_ABSRATE1 = 289,	 //0 1 0 
	ID_DA_H_PM_L_ABSRATE2 = 290,	 //0 1 0 
	ID_DP_H_PM_L_ABSANG = 291,	 //0 0 1 
	ID_DP_H_PM_L_ABSRATE = 292,	 //0 0 1 
	ID_DC_H_PM_L_ABSANG1 = 293,	 //0 0 1 
	ID_DC_H_PM_L_ABSANG2 = 294,	 //0 0 1 
	ID_DC_H_PM_L_ABSRATE1 = 295,	 //0 0 1 
	ID_DC_H_PM_L_ABSRATE2 = 296,	 //0 0 1 
	ID_H_TEST1 = 297,	 //0 0 1 dummy for testing hip
	ID_H_TEST2 = 298,	 //0 0 1 dummy for testing hip
	ID_H_TEST3 = 299,	 //0 0 1 dummy for testing hip
	ID_H_TEST4 = 300,	 //0 0 1 dummy for testing hip
	ID_H_TEST5 = 301,	 //0 0 1 dummy for testing hip
	ID_P_F_PP_OUTER_BIAS = 302,	 //1 0 1 
	ID_C_F_ST_F_ANG = 303,	 //4 0 1 
	ID_C_F_ST_F_RATE = 304,	 //0.2 0 1 
	ID_C_F_PP_F_ANG = 305,	 //10 0 1 
	ID_C_F_PP_F_ANG2 = 306,	 //8 0 1 
	ID_C_F_PP_F_RATE = 307,	 //0 0 1 spiky data. so set to zero
	ID_C_F_AP_F_ANG = 308,	 //8 0 1 
	ID_C_F_AP_F_RATE = 309,	 //0 0 1 
	ID_A_F_PP_A0 = 310,	 //0 0 1 current for prepush
	ID_C_F_FU_F_ANG = 311,	 //1.5 0 1 
	ID_C_F_FU_F_RATE = 312,	 //0.1 0 1 
	ID_C_F_FD_F_ANG = 313,	 //1.5 0 1 
	ID_C_F_FD_F_RATE = 314,	 //0.1 0 1 
	ID_C_FO_SST_F_ANG = 315,	 //4 0 1 
	ID_C_FO_SST_F_RATE = 316,	 //0.2 0 1 
	ID_C_F_SST_F_ANG = 317,	 //30 0 1 
	ID_C_F_SST_F_RATE = 318,	 //0.3 0 1 
	ID_P_F_PP_L_ABSANG = 319,	 //0.12 0 1 was 0.07 for barton record walk
	ID_P_F_PP_F_ABSANG = 320,	 //1.7 0 1 absolute feet angle for push-off
	ID_P_FO_PP_THEIGHT = 321,	 //0.012 0 1 push-off trigger for outer foot
	ID_P_FI_PP_THEIGHT = 322,	 //0.012 0 1 push-off trigger for inner foot
	ID_P_F_AP_F_ANG = 323,	 //0 0 1 
	ID_P_F_FU_H_ANG = 324,	 //0.1 0 1 was 0.13 for barton record walk
	ID_P_F_FU_F_TANG = 325,	 //0.2 0 1 
	ID_P_F_ST_F_TANG = 326,	 //2 0 1 
	ID_P_F_PP_F_TANG = 327,	 //0.2 0 1 was 0.5 for barton record walk
	ID_P_F_PP_F_TANG2 = 328,	 //0.3 0 1 
	ID_P_F_PP_FRAC_ANG = 329,	 //0.5 0 1 angle turned for prepush completion
	ID_P_F_AP_F_TANG = 330,	 //0 0 1 
	ID_P_F_FD_F_TANG = 331,	 //2 0 1 
	ID_P_F_SST_F_TANG = 332,	 //2 0 1 
	ID_P_FO_SST_F_TANG = 333,	 //2 0 1 
	ID_P_F_FU_F_CABL_STRETCH = 334,	 //0.07 0 1 cable stretch
	ID_P_F_AP_TIME = 335,	 //30 0 1 maximum time for after-push in ms
	ID_P_F_PP_F_LRATE = 336,	 //0.5 0 1 rate below which emergency prepush should occur
	ID_P_F_PP_F_HRATE = 337,	 //0.8 0 1 rate above which pre-push should be cut-off
	ID_P_F_PP_TIME = 338,	 //10 0 1 trigger for double-stance push-off for missed prepush
	ID_D_F_ON = 339,	 //1 0 1 foot discrete control on
	ID_DA_F_PP_L_ABSRATE = 340,	 //0 1 0 
	ID_DA_F_PP_L_ABSRATE2 = 341,	 //0 1 0 
	ID_DP_F_PP_L_ABSRATE = 342,	 //0.65 0 1 
	ID_DC_F_PP_L_ABSRATE = 343,	 //5 0 1 gain on dampness in pp control
	ID_DC_F_PP_L_ABSRATE2 = 344,	 //0.5 0 1 gain on angle in pp control
	ID_F_TEST1 = 345,	 //0 0 1 dummy for testing feet
	ID_F_TEST2 = 346,	 //0 0 1 dummy for testing feet
	ID_F_TEST3 = 347,	 //0 0 1 dummy for testing feet
	ID_F_TEST4 = 348,	 //0 0 1 dummy for testing feet
	ID_F_TEST5 = 349,	 //0 0 1 dummy for testing feet
	ID_F_TEST6 = 350,	 //0 0 1 dummy for testing feet
	ID_F_TEST7 = 351,	 //0 0 1 dummy for testing feet
	ID_F_TEST8 = 352,	 //0 0 1 dummy for testing feet
	ID_P_S_NULL_H_TANG = 353,	 //0.1 0 1 hip trigger angle
	ID_P_S_ILST_S_MAXANG = 354,	 //100 0 1 
	ID_P_S_ILSW_S_MAXANG = 355,	 //0 0 1 
	ID_C_S_NULL_S_ANG = 356,	 //0 0 1 gain of 0.002 works well
	ID_C_S_NULL_S_RATE = 357,	 //0 0 1 
	ID_P_S_NULL_S_MAX_CUR = 358,	 //0 0 1 max pwm for steering was 75
	ID_P_S_ILST_TWITCH_FRAC = 359,	 //1 0 0 fraction by which legs should twitch in stance a number between one and minus one
	ID_P_S_ILST_TWITCH_TIME = 360,	 //1 0 0 twice this time is the time for the twitch to take place in stance
	ID_D_S_NULL_S_DANG = 361,	 //0 1 0 desired steer angle commanded by rc
	ID_P_S_NULL_RC_DEADBAND = 362,	 //0.02 0 1 dead band for rc control
	ID_P_UI_PP2HS_TTIME = 363,	 //70 0 1 set led if time is more that this time in ms
	ID_A_T_RC0_NORM = 364,	 //0 1 0 normalized rc0 value
	ID_A_T_RC1_NORM = 365,	 //0 1 0 normalized rc1 value
	ID_T_TEST1 = 366,	 //0 1 0 
	ID_T_TEST2 = 367,	 //0 1 0 
	ID_T_TEST3 = 368,	 //0 1 0 
	ID_T_TEST4 = 369,	 //0 1 0 
	ID_T_TEST5 = 370,	 //0 1 0 
	ID_T_TEST6 = 371,	 //0 1 0 
	ID_ABSOLUTE_COMP_TIME = 372,	 //0 0 1 
	ID_GBRL_DELTA = 373,	 //0.02 0 1 Percent change for parameter perturbation
	ID_GBRL_MAX_STEPS = 374,	 //8 0 1 Number of steps per average reward computation
	ID_GBRL_REWARD = 375,	 //0 1 0 Current value of the GBRL reward function (usually Cost of Transport)
	ID_GBRL_POWER = 376,	 //0 1 0 Current estimated power consumption
	ID_GBRL_VELOCITY = 377,	 //0 1 0 Current estimated velocity of Ranger
	ID_GBRL_COT = 378,	 //0 1 0 Current estimated Cost of Transport
	ID_GBRL_CURRENT_PARAM = 379,	 //0 1 0 Current parameter being perturbed
	ID_GBRL_STEP_TIME = 380,	 //0 1 0 Time of the previous step
	ID_GBRL_STEP_LENGTH = 381,	 //0 1 0 Length of the previous step
	ID_GBRL_STEP_VELOCITY = 382,	 //0 1 0 Avg. Velocity of the previous step
	ID_GBRL_STABILITY = 383,	 //0 1 0 Estimated stability of Ranger
	ID_LV_START,	 //   
	ID_LV_CH_0,	 //   
	ID_LV_CH_1,	 //   
	ID_LV_CH_2,	 //   
	ID_LV_CH_3,	 //   
	ID_LV_CH_4,	 //   
	ID_LV_CH_5,	 //   
	ID_LV_CH_6,	 //   
	ID_LV_CH_7,	 //   
	ID_LV_CH_8,	 //   
	ID_LV_CH_9,	 //   
	ID_LV_CH_10,	 //   
	ID_LV_CH_11,	 //   
	ID_LV_CH_12,	 //   
	ID_LV_CH_13,	 //   
	ID_LV_CH_14,	 //   
	ID_LV_CH_15,	 //   
	ID_LV_CH_16,	 //   
	ID_LV_CH_17,	 //   
	ID_LV_CH_18,	 //   
	ID_LV_CH_19,	 //   
	ID_LV_CH_20,	 //   
	ID_LV_CH_21,	 //   
	ID_LV_CH_22,	 //   
	ID_LV_CH_23,	 //   
	ID_LV_CH_24,	 //   
	ID_LV_CH_25,	 //   
	ID_LV_CH_26,	 //   
	ID_LV_CH_27,	 //   
	ID_LV_CH_28,	 //   
	ID_LV_CH_29,	 //   
	ID_LV_CH_30,	 //   
	ID_LV_CH_31,	 //   
	ID_LV_CH_32,	 //   
	ID_LV_CH_33,	 //   
	ID_LV_CH_34,	 //   
	ID_LV_CH_35,	 //   
	ID_LV_CH_36,	 //   
	ID_LV_CH_37,	 //   
	ID_LV_CH_38,	 //   
	ID_LV_CH_39,	 //   
	ID_LV_CH_40,	 //   
	ID_LV_CH_41,	 //   
	ID_LV_CH_42,	 //   
	ID_LV_CH_43,	 //   
	ID_LV_CH_44,	 //   
	ID_LV_CH_45,	 //   
	ID_LV_CH_46,	 //   
	ID_LV_CH_47,	 //   
	ID_LV_VERSION,	 //   
	ID_LAST
} CAN_ID;


#endif

